---
x-networkpolicy:
  - librechat

services:
  excalidraw:
    image: docker.io/excalidraw/excalidraw:latest
    labels:
      kompose.service.expose: draw.${DOMAIN}
    ports:
      - 80

  mcp:
    image: docker.io/oven/bun:latest
    labels:
      kompose.service.expose: draw.mcp.${DOMAIN}
    entrypoint:
      - sh
    command:
      - -euxc
      - |-
        bunx degit excalidraw/excalidraw-mcp /tmp/app
        cd -- /tmp/app
        sed -E --in-place -e 's/0\.0\.0\.0/::/g' -- src/main.ts
        bun install --production
        exec bun src/main.ts
    environment:
      PORT: 8080
    ports:
      - 8080
