---
x-networkpolicy:
  - navidrome
  - servarr

x-k8s:
  # openssh-server.komposed-openssh-server.svc.cluster.local
  - apiVersion: v1
    kind: Service
    metadata:
      name: openssh-server-fwd
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - IPv6
        - IPv4
      selector:
        io.kompose.service: &service openssh-server
      ports:
        - name: webdav
          port: 5050
          targetPort: 5050
        - name: proxy
          port: 8080
          targetPort: 8080

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: openssh-server-ingress
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      podSelector:
        matchLabels:
          io.kompose.service: *service
      policyTypes:
        - Ingress
      ingress:
        - ports:
            - port: 2222
              protocol: TCP
        - from:
            - podSelector: {}
          ports:
            - port: 5050
              protocol: TCP
            - port: 8080
              protocol: TCP

services:
  rclone:
    image: ghcr.io/rclone/rclone:latest
    labels:
      kompose.volume.type: hostPath
      jq.mixin: |-
        {
          "containers": [
            {
              "volumeMounts": [
                { "mountPropagation": "Bidirectional" },
                {
                  "mountPath": "/data",
                  "name": "rclone-data",
                  "mountPropagation": "Bidirectional"
                }
              ]
            }
          ],
          "volumes": [
            null,
            {
              "name": "rclone-data",
              "hostPath": { "path": "/var/lib/local/rclone" }
            }
          ]
        }
    privileged: true
    healthcheck:
      test:
        - CMD
        - find
        - /data
        - "-maxdepth"
        - "1"
        - "-print"
        - "-quit"
    command:
      - mount
      - --allow-non-empty
      - --allow-other
      - --config=/dev/null
      - --default-permissions
      - --transfers=8
      - --dir-cache-time=60s
      - --poll-interval=30s
      - --vfs-refresh
      - --vfs-cache-mode=full
      - --webdav-vendor=nginx
      - --webdav-pacer-min-sleep=0
      - --read-only
      - --vfs-fast-fingerprint
      - --webdav-url=http://openssh-server-fwd.komposed-openssh-server.svc.cluster.local:5050
      - :webdav:/
      - /data
    volumes:
      - /dev/fuse:/dev/fuse

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    labels:
      kompose.service.nodeport.port: 30022
      kompose.service.type: nodeport
    environment:
      PUBLIC_KEY_DIR: /srv
    ports:
      - 2222
    volumes:
      - ./authorized_keys:/srv/authorized_keys:ro
      - ./sshd_config:/config/sshd/sshd_config.d/forward.conf:ro
