# https://github.com/ZhiYi-R/moon-bridge/blob/main/config.example.yml
---
mode: Transform

server:
  auth_token: m5_assert([ENV_MINIFLUX_PASSWORD])
  addr: :38440

defaults:
  max_tokens: 1048576

models:
  deepseek/deepseek-v4-pro:
    web_search:
      support: auto
    extensions:
      deepseek_v4:
        enabled: true

providers:
  deepseek:
    api_key: m5_assert([ENV_DEEPSEEK_API_KEY])
    base_url: https://api.deepseek.com/anthropic
    offers:
      - model: deepseek/deepseek-v4-pro
