---
services:
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    labels:
      kompose.service.expose: redis.${DOMAIN}
    environment:
      ADDRESS: "::"
      REDIS_HOSTS: lo:redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local:6379:0:${COMPOSE_PROJECT_NAME}
    ports:
      - 8081

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.service.nodeport.port: 30001
      kompose.service.type: nodeport
    command:
      - redis-server
      # - --requirepass
      # - ${COMPOSE_PROJECT_NAME}
    ports:
      - 6379
    volumes:
      - data:/data

  mcp:
    image: python:latest
    labels:
      kompose.service.expose: redis.mcp.${DOMAIN}
    deploy:
      resources:
        limits:
          memory: 250M
    entrypoint:
      - sh
    command:
      - -euxc
      - |-
        pip install -- fastmcp redis-mcp-server
        tee -- /tmp/mcp.json <<- 'JSON'
        {"mcpServers": {"redis": {"command": "redis-mcp-server", "args": ["--url", "redis://redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local:6379"]}}}
        JSON
        exec fastmcp run /tmp/mcp.json --transport http --host ''
    ports:
      - 8000
    volumes:
      - pip-cache:/root/.cache/pip

volumes:
  data:
  pip-cache:
