---
services:
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    labels:
      kompose.service.expose: redis.${DOMAIN}
    environment:
      ADDRESS: "::"
      REDIS_HOSTS: lo:redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local:6379:0:${COMPOSE_PROJECT_NAME}
    ports:
      - 8081

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.service.nodeport.port: 30001
      kompose.service.type: nodeport
    command:
      - redis-server
      # - --requirepass
      # - ${COMPOSE_PROJECT_NAME}
    ports:
      - 6379
    volumes:
      - data:/data

  # mcp:
  #   image: docker.io/mcp/redis:latest
  #   # labels:
  #     # kompose.service.expose: mcp-redis.${DOMAIN}
  #   environment:
  #     REDIS_HOST: redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local
  #   ports:
  #     - 8080

volumes:
  data:
