---
services:
  librechat:
    image: registry.librechat.ai/danny-avila/librechat-dev:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: chat.${DOMAIN}
      kompose.service.group: &librechat librechat
    environment:
      ANTHROPIC_API_KEY:
      HOST: "::"
      HTTP_PROXY: &proxy http://proxy.kompsed-hostproxy.svc.cluster.local:1080
      HTTPS_PROXY: *proxy
      JWT_REFRESH_SECRET:
      JWT_SECRET:
      MEILI_HOST: http://meilisearch.kompsed-librechat.svc.cluster.local:7700
      MONGO_URI: mongodb://mongo.kompsed-librechat.svc.cluster.local:27017/
      NO_INDEX: true
      NO_PROXY: localhost,127.0.0.1,::1,.svc.cluster.local
      OPENAI_API_KEY:
      OPENROUTER_KEY:
      RAG_API_URL: http://rag-api.kompsed-librechat.svc.cluster.local:8000
      REDIS_URI: redis://localhost:6379
      USE_REDIS: true
      XAI_API_KEY:
    ports:
      - 3080
    volumes:
      - ./librechat.yml:/app/librechat.yaml:ro
      - images:/app/client/public/images
      - logs:/app/api/logs
      - uploads:/app/uploads

  mongo:
    image: docker.io/library/mongo:8
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    command:
      - mongod
      - --noauth
      - --ipv6
    ports:
      - 27017
    volumes:
      - /var/lib/local/librechat/mongo:/data/db

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.group: *librechat
    ports:
      - 6379
    volumes:
      - redis:/data

  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.35.1
    labels:
      kompose.controller.type: statefulset
    environment:
      MEILI_HOST: http://meilisearch:7700
      MEILI_NO_ANALYTICS: true
    ports:
      - 7700
    volumes:
      - meilisearch:/meili_data

  pg:
    image: docker.io/pgvector/pgvector:pg18-trixie
    labels:
      kompose.controller.type: statefulset
    environment:
      POSTGRES_DB: &pgdb ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: &pgpass ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: &pguser ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql

  rag-api:
    image: registry.librechat.ai/danny-avila/librechat-rag-api-dev-lite:latest
    labels:
      kompose.controller.type: statefulset
    environment:
      DB_HOST: pg
      POSTGRES_DB: *pgdb
      POSTGRES_PASSWORD: *pgpass
      POSTGRES_USER: *pguser
      RAG_HOST: "::"
    ports:
      - 8000

volumes:
  images:
  logs:
  meilisearch:
  pgdata:
  redis:
  uploads:
