# https://github.com/danny-avila/LibreChat/blob/main/librechat.example.yaml
---
version: 1.3.9

mcpSettings:
  allowedDomains:
    - "*.svc.cluster.local"

mcpServers:
  bifrost:
    type: http
    url: http://bifrost.kompsed-bifrost.svc.cluster.local:8080/mcp
  kubernetes:
    type: http
    url: http://kubernetes.kompsed-mcp.svc.cluster.local:8080/mcp

memory:
  disabled: true
