# https://github.com/danny-avila/LibreChat/blob/main/librechat.example.yaml
---
version: 1.3.9

mcpSettings:
  allowedDomains:
    - "*.svc.cluster.local"

mcpServers:
  bifrost:
    type: http
    url: http://bifrost.komposed-bifrost.svc.cluster.local:8080/mcp
  excalidraw:
    type: http
    url: http://mcp.komposed-excalidraw.svc.cluster.local:8080/mcp
  kubernetes:
    type: http
    url: http://mcp.komposed-k8s-mcp.svc.cluster.local:8080/mcp
  playwright:
    type: http
    url: http://playwright.komposed-mcp.svc.cluster.local:8080/mcp
  redis:
    type: http
    url: http://mcp.komposed-redis-commander.svc.cluster.local:8000/mcp
  youtube:
    type: http
    url: http://youtube-transcript.komposed-mcp.svc.cluster.local:8080/mcp

memory:
  disabled: true

endpoints:
  custom:
    - name: "deepseek"
      apiKey: "${DEEPSEEK_API_KEY}"
      baseURL: "https://api.deepseek.com"
      models:
        default:
          - "deepseek-v4-pro"
          - "deepseek-v4-flash"
        fetch: true
      titleConvo: true
      titleModel: "deepseek-v4-flash"
      modelDisplayLabel: "DeepSeek"
