# https://github.com/danny-avila/LibreChat/blob/main/librechat.example.yaml
---
version: 1.3.6

webSearch:
  searxngInstanceUrl: http://searxng.kompsed-searx.svc.cluster.local:8080

mcpServers:
  searx:
    url: http://searx.kompsed-mcp.svc.cluster.local:8080/mcp
  context7:
    url: http://context7.kompsed-mcp.svc.cluster.local:8080/mcp
  dockerhub:
    url: http://dockerhub.kompsed-mcp.svc.cluster.local:8080/mcp
  terraform:
    url: http://terraform-proxy.kompsed-mcp.svc.cluster.local:8080/mcp
