# https://github.com/danny-avila/LibreChat/blob/main/librechat.example.yaml
---
version: 1.3.6

webSearch:
  searxngApiKey: ""
  searxngInstanceUrl: http://searxng.kompsed-searx.svc.cluster.local:8080

mcpSettings:
  allowedDomains:
    - "*.svc.cluster.local"
    - "microsoft.com"

mcpServers:
  searx:
    type: http
    url: http://searx.kompsed-mcp.svc.cluster.local:8080/mcp
  context7:
    type: http
    url: http://context7.kompsed-mcp.svc.cluster.local:8080/mcp
  dockerhub:
    type: http
    url: http://dockerhub.kompsed-mcp.svc.cluster.local:3000/mcp
  terraform:
    type: http
    url: http://terraform-proxy.kompsed-mcp.svc.cluster.local:1080/mcp

  microsoft-docs:
    url: https://learn.microsoft.com/api/mcp
