# NL

add element inet user internal_ifs { m5_assert([ENV_MACVLAN_IFS]) }

# m5_for([IF], [
add element inet user isolated_ifs { IF }
# ], m5_or([ENV_IOT_IFS], []))

add element inet user internal_ports { tcp . http }
