---
services:
  plex:
    image: quay.io/plexinc/pms-docker:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: plex.${DOMAIN}
      kompose.volume.type: hostPath
    environment: {}
    ports:
      - 32400
    volumes:
      - /var/lib/local/plexmediaserver:/config
      - /var/lib/local/rclone/media:/media:ro
