---
services:
  soju:
    image: codeberg.org/emersion/soju:latest
    labels:
      kompose.service.nodeport.port: 30002
      kompose.service.type: nodeport
    ports:
      - 6667
    volumes:
      - ./soju.conf:/soju-config:ro

  auth:
    image: docker.io/library/nginx:latest
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    ports:
      - 80
    configs:
      - source: auth_conf
        target: /etc/nginx/nginx.conf
    volumes:
      - /run/local/nginx:/run/local/nginx:ro

  pg:
    image: docker.io/library/postgres:18
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - /var/lib/local/soju:/var/lib/postgresql

configs:
  auth_conf:
    file: ./auth.nginx
