accept-proxy-ip     192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 fd00::/8
auth                http http://auth.kompsed-soju.svc.cluster.local/
db                  postgres "host=pg user=kompsed-soju password=kompsed-soju dbname=kompsed-soju sslmode=disable"
enable-user-on-auth true
hostname            irc.m5_assert([ENV_DOMAIN])
http-origin         *
listen              irc+insecure://
listen              unix+admin://
message-store       db

# kubectl --namespace kompsed-soju exec deployments/soju -- sojuctl
