hostname        irc.m5_assert([ENV_DOMAIN])
listen          irc+insecure://
listen          unix+admin://
db              postgres "host=pg user=kompsed-soju password=kompsed-soju dbname=kompsed-soju sslmode=disable"
message-store   db
http-origin     *
accept-proxy-ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 fd00::/8

# kubectl --namespace kompsed-soju exec deployments/soju -- sojuctl
