accept-proxy-ip     192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 fd00::/8
auth                http http://auth.komposed-soju.svc.cluster.local/
db                  postgres "host=pg user=komposed-soju password=komposed-soju dbname=komposed-soju sslmode=disable"
enable-user-on-auth true
hostname            irc.m5_assert([ENV_DOMAIN])
http-origin         *
listen              irc+insecure://
listen              unix+admin://
message-store       db

# kubectl --namespace komposed-soju exec deployments/soju -- sojuctl
