---
x-k8s:
  # m5_for([PROXY_NS], [
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: addn-policy-PROXY_NS
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kompsed-PROXY_NS
  # ], litellm)

services:
  langfuse-web:
    image: ghcr.io/langfuse/langfuse:latest
    labels:
      kompose.service.expose: langfuse.${DOMAIN}
    environment: &langfuse-env
      AUTH_DISABLE_SIGNUP: true
      CLICKHOUSE_CLUSTER_ENABLED: false
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse.${COMPOSE_PROJECT_NAME}.svc.cluster.local:9000
      CLICKHOUSE_PASSWORD: &chpw ${COMPOSE_PROJECT_NAME}
      CLICKHOUSE_URL: http://clickhouse.${COMPOSE_PROJECT_NAME}.svc.cluster.local:8123
      CLICKHOUSE_USER: &chusr ${COMPOSE_PROJECT_NAME}
      DATABASE_URL: postgres://${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_NAME}@pg.${COMPOSE_PROJECT_NAME}.svc.cluster.local/${COMPOSE_PROJECT_NAME}
      ENCRYPTION_KEY:
      HOSTNAME: "::"
      LANGFUSE_INIT_USER_EMAIL:
      LANGFUSE_INIT_ORG_ID: ${COMPOSE_PROJECT_NAME}
      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_EMAIL}
      LANGFUSE_INIT_USER_PASSWORD:
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: &s3keyid ${COMPOSE_PROJECT_NAME}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://versitygw.${COMPOSE_PROJECT_NAME}.svc.cluster.local:7070
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: true
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: /
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: &s3key ${COMPOSE_PROJECT_NAME}
      NEXTAUTH_SECRET:
      NEXTAUTH_URL: https://langfuse.${DOMAIN}
      REDIS_AUTH: &redispw ${COMPOSE_PROJECT_NAME}
      REDIS_HOST: redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local
      REDIS_PORT: 6379
      SALT:
      TELEMETRY_ENABLED: false
    ports:
      - 3000

  langfuse-worker:
    image: ghcr.io/langfuse/langfuse-worker:latest
    environment:
      <<: *langfuse-env
    ports:
      - 3030

  versitygw:
    image: ghcr.io/versity/versitygw:latest
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      ROOT_ACCESS_KEY: *s3keyid
      ROOT_SECRET_KEY: *s3key
    command:
      - posix
      - /data
    ports:
      - 7070
    volumes:
      - /var/lib/local/langfuse/versitygw:/data/langfuse

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:latest
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      CLICKHOUSE_USER: *chusr
      CLICKHOUSE_PASSWORD: *chpw
    ports:
      - 8123
      - 9000
    volumes:
      - /var/lib/local/langfuse/clickhouse:/var/lib/clickhouse

  pg:
    image: docker.io/library/postgres:18
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - /var/lib/local/langfuse/postgresql:/var/lib/postgresql

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    ports:
      - 6379
    command:
      - --requirepass
      - *redispw
    volumes:
      - data:/data

volumes:
  data:
