---
services:
  langfuse-web:
    image: ghcr.io/langfuse/langfuse:3
    labels:
      kompose.service.expose: langfuse.${DOMAIN}
    environment: &langfuse-env
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse.${COMPOSE_PROJECT_NAME}.svc.cluster.local:9000
      CLICKHOUSE_URL: http://clickhouse.${COMPOSE_PROJECT_NAME}.svc.cluster.local:8123
      DATABASE_URL: postgres://${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_NAME}@pg.${COMPOSE_PROJECT_NAME}.svc.cluster.local/${COMPOSE_PROJECT_NAME}
      ENCRYPTION_KEY: ${LANGFUSE_ENCRYPTION_KEY}
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio.minio.svc.cluster.local:9000
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: true
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: events/
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      NEXTAUTH_SECRET: ${LANGFUSE_NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://langfuse.${DOMAIN}
      REDIS_HOST: redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local
      REDIS_PORT: 6379
      SALT: ${LANGFUSE_SALT}
      TELEMETRY_ENABLED: false
    ports:
      - 3000

  langfuse-worker:
    image: ghcr.io/langfuse/langfuse-worker:3
    environment:
      <<: *langfuse-env

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:latest
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: "1"
    ports:
      - 8123
      - 9000
    volumes:
      - /var/lib/local/langfuse/clickhouse:/var/lib/clickhouse

  pg:
    image: docker.io/library/postgres:18
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - /var/lib/local/langfuse/postgresql:/var/lib/postgresql

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    ports:
      - 6379
    volumes:
      - data:/data

volumes:
  data:
