---
x-k8s:
  # m5_for([PROXY_NS], [
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: addn-policy-PROXY_NS
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kompsed-PROXY_NS
  # ], mcp, librechat)

services:
  firecrawl:
    image: ghcr.io/firecrawl/firecrawl:latest
    labels:
      kompose.service.group: &firecrawl firecrawl
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      HOST: "::"
      NUQ_DATABASE_URL: postgres://${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_NAME}@pg.${COMPOSE_PROJECT_NAME}.svc.cluster.local/postgres
      NUQ_RABBITMQ_URL: amqp://rabbitmq:5672
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright:3003/scrape
      REDIS_URL: redis://localhost:6379
      SEARXNG_ENDPOINT: http://searxng.kompsed-searx.svc.cluster.local:8080
    ports:
      - 3002

  playwright:
    image: ghcr.io/firecrawl/playwright-service:latest
    environment:
      BLOCK_MEDIA: true
      PROXY_SERVER: http://proxy.kompsed-hostproxy.svc.cluster.local:1080
    ports:
      - 3003

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.service.group: *firecrawl
    ports:
      - 6379
    volumes:
      - redis:/data

  rabbitmq:
    image: docker.io/library/rabbitmq:management
    labels:
      kompose.controller.type: statefulset
    ports:
      - 5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  pg:
    image: ghcr.io/firecrawl/nuq-postgres:latest
    labels:
      kompose.controller.type: statefulset
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
  rabbitmq:
  redis:
