---
x-networkpolicy:
  - bifrost
  - librechat

services:
  playwright:
    image: mcr.microsoft.com/playwright/mcp:latest
    labels:
      kompose.service.expose: playwright.mcp.${DOMAIN}
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      PLAYWRIGHT_MCP_ALLOWED_HOSTS: "*"
      PLAYWRIGHT_MCP_HOST: "::"
      PLAYWRIGHT_MCP_ISOLATED: true
      PLAYWRIGHT_MCP_OUTPUT_DIR: /tmp/playwright-home
      PLAYWRIGHT_MCP_PORT: 8080
      PLAYWRIGHT_MCP_PROXY_SERVER: socks5://proxy.kompsed-hostproxy.svc.cluster.local:1080
      PLAYWRIGHT_MCP_SANDBOX: true
      PLAYWRIGHT_MCP_SNAPSHOT_MODE: none
    ports:
      - 8080
    volumes:
      - playwright:/tmp/playwright-home

  time: &pip
    image: python:latest
    deploy:
      resources:
        limits:
          memory: 250M
    entrypoint:
      - sh
    command:
      - -euxc
      - |-
        pip install -- mcp-proxy mcp-server-time
        exec mcp-proxy --pass-environment --host=:: --port=8080 --transport=streamablehttp -- mcp-server-time
    ports:
      - 8080
    volumes:
      - pip-cache:/root/.cache/pip

  youtube-transcript:
    <<: *pip
    labels:
      kompose.service.expose: youtube.mcp.${DOMAIN}
    command:
      - -euxc
      - |-
        pip install -- mcp-proxy mcp-youtube-transcript
        exec mcp-proxy --pass-environment --host=:: --port=8080 --transport=streamablehttp -- mcp-youtube-transcript
    environment:
      HTTP_PROXY: http://proxy.kompsed-hostproxy.svc.cluster.local:1080
      HTTPS_PROXY: http://proxy.kompsed-hostproxy.svc.cluster.local:1080

volumes:
  pip-cache:
  playwright:
