---
x-networkpolicy:
  - bifrost
  - librechat

services:
  playwright:
    image: mcr.microsoft.com/playwright/mcp:latest
    labels:
      kompose.service.expose: playwright.mcp.${DOMAIN}
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      PLAYWRIGHT_MCP_ALLOWED_HOSTS: "*"
      PLAYWRIGHT_MCP_HOST: "::"
      PLAYWRIGHT_MCP_ISOLATED: true
      PLAYWRIGHT_MCP_OUTPUT_DIR: /tmp/playwright-home
      PLAYWRIGHT_MCP_PORT: 8080
      PLAYWRIGHT_MCP_PROXY_SERVER: socks5://proxy.kompsed-hostproxy.svc.cluster.local:1080
      PLAYWRIGHT_MCP_SANDBOX: true
    ports:
      - 8080
    volumes:
      - playwright:/tmp/playwright-home

  time: &fastmcp
    image: python:latest
    deploy:
      resources:
        limits:
          memory: 250M
    entrypoint:
      - sh
    command:
      - -euxc
      - |-
        pip install -- fastmcp mcp-server-time
        tee -- /tmp/mcp.json <<- 'JSON'
        {"mcpServers": {"time": {"command": "mcp-server-time"}}}
        JSON
        exec fastmcp run /tmp/mcp.json --transport http --host ''
    ports:
      - 8000
    volumes:
      - pip-cache:/root/.cache/pip

  youtube-transcript:
    <<: *fastmcp
    labels:
      kompose.service.expose: youtube.mcp.${DOMAIN}
    environment:
      HTTP_PROXY: &proxy http://proxy.kompsed-hostproxy.svc.cluster.local:1080
      HTTPS_PROXY: *proxy
    command:
      - -euxc
      - |-
        pip install -- fastmcp mcp-youtube-transcript
        tee -- /tmp/mcp.json <<- 'JSON'
        {"mcpServers": {"youtube": {"command": "mcp-youtube-transcript"}}}
        JSON
        exec fastmcp run /tmp/mcp.json --transport http --host ''

volumes:
  pip-cache:
  playwright:
