---
x-networkpolicy:
  - bifrost
  - librechat

services:
  playwright:
    image: mcr.microsoft.com/playwright/mcp:latest
    labels:
      kompose.service.expose: playwright.mcp.${DOMAIN}
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      PLAYWRIGHT_MCP_ALLOWED_HOSTS: "*"
      PLAYWRIGHT_MCP_HOST: "::"
      PLAYWRIGHT_MCP_ISOLATED: true
      PLAYWRIGHT_MCP_OUTPUT_DIR: /tmp/playwright-home
      PLAYWRIGHT_MCP_PORT: 8080
      PLAYWRIGHT_MCP_PROXY_SERVER: socks5://proxy.kompsed-hostproxy.svc.cluster.local:1080
      PLAYWRIGHT_MCP_SANDBOX: true
      PLAYWRIGHT_MCP_SNAPSHOT_MODE: none
    ports:
      - 8080
    volumes:
      - playwright:/tmp/playwright-home

  time:
    image: docker.io/supercorp/supergateway:uvx
    deploy:
      resources:
        limits:
          memory: 256MB
    command:
      - --outputTransport=streamableHttp
      - --stdio
      - uvx mcp-server-time
    ports:
      - 8000

volumes:
  playwright:
