# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.expose: claw.${DOMAIN}
      kompose.service.group: &svcgrp openclaw
      kompose.volume.type: hostPath
      jq.mixin: |-
        {
          "containers": [
            null,
            {
              "volumeMounts": [
                {
                  "mountPath": "/home/node/.openclaw/openclaw.json",
                  "name": "openclaw",
                  "subPath": "openclaw.json"
                }
              ]
            }
          ],
          "volumes": [
            null,
            {
              "name": "openclaw",
              "configMap": { "name": "openclaw" }
            }
          ]
        }
    environment:
      DOMAIN:
      OPENCLAW_DISABLE_BONJOUR: 1
      OPENCLAW_GATEWAY_TOKEN:
    configs:
      - source: openclaw
        target: /home/node/.openclaw/openclaw.json
    ports:
      - 8080

  nginx:
    image: docker.io/library/nginx:latest
    labels:
      kompose.controller.type: statefulset
      kompose.service.group: *svcgrp
    volumes:
      - ./main.nginx:/etc/nginx/nginx.conf:ro

configs:
  openclaw:
    file: ./openclaw.json
  nginx:
    file: ./main.nginx
