---
x-k8s:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      labels:
        io.kompose.service: &mitm mitmproxy
      name: *mitm
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      parentRefs:
        - name: traefik-gateway
          namespace: kube-system
      hostnames:
        - mitm.m5_assert([ENV_DOMAIN])
      rules:
        - filters:
            - type: RequestHeaderModifier
              requestHeaderModifier:
                set:
                  - name: Authorization
                    value: Bearer ${COMPOSE_PROJECT_NAME}
          backendRefs:
            - name: *mitm
              port: 8081

  - apiVersion: v1
    kind: Service
    metadata:
      name: mitmproxy-np
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      type: NodePort
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - IPv6
        - IPv4
      selector:
        io.kompose.service: &svc mitmproxy
      ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30003

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: nodeport
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      podSelector:
        matchLabels:
          io.kompose.service: *svc
      ingress:
        - ports:
            - protocol: TCP
              port: 8080

services:
  mitmproxy:
    image: ghcr.io/mitmproxy/mitmproxy:latest
    command:
      - mitmweb
    ports:
      - 8081
    volumes:
      - ./conf.yml:/home/mitmproxy/.mitmproxy/config.yaml:ro
