# https://github.com/unclecode/crawl4ai/blob/main/deploy/docker/config.yml
---
crawler:
  browser:
    kwargs:
      enable_stealth: true
    extra_args:
      - --disable-dev-shm-usage
      - --disable-gpu
      - --disable-software-rasterizer
      - --disable-web-security
      - --proxy-server=socks5://proxy.kompsed-hostproxy.svc.cluster.local:1080
