---
x-k8s:
  # m5_for([PROXY_NS], [
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: addn-policy-PROXY_NS
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kompsed-PROXY_NS
  # ], librechat)

services:
  crawl4ai:
    image: docker.io/unclecode/crawl4ai:latest
    labels:
      kompose.service.expose: crawl4ai.${DOMAIN}
    entrypoint:
      - sh
      - -euxc
      - |-
        sed -i -e 's|0\.0\.0\.0:11235|[[::]]:11235|' -- /app/supervisord.conf
        exec supervisord -c supervisord.conf
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 11235
    volumes:
      - ./config.yml:/app/config.yml:ro
