---
x-networkpolicy:
  - mcp

services:
  crawl4ai:
    image: docker.io/unclecode/crawl4ai:latest
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      CRAWL4AI_API_TOKEN: crawl4ai
      GUNICORN_BIND: "[[::]]:11235"
      REDIS_PASSWORD: crawl4ai
    ports:
      - 11235
    volumes:
      - ./config.yml:/app/config.yml:ro
