# https://docs.litellm.ai/docs/proxy/configs
---
general_settings:
  database_url: os.environ/DATABASE_URL
  forward_client_headers_to_llm_api: true
  forward_llm_provider_auth_headers: true

litellm_settings:
  callbacks: ["langfuse_otel"]
  use_redis_transaction_buffer: true
  cache: true
  json_logs: false
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST

model_list:
  - model_name: "*"
    litellm_params:
      model: "*"
