---
x-k8s:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: auth
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      headers:
        customRequestHeaders:
          Authorization: Bearer sk-litellm-llmlite
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: litellm
      namespace: ${COMPOSE_PROJECT_NAME}
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`litellm.${DOMAIN}`) && PathPrefix(`/v1/messages`)
          kind: Rule
          services:
            - name: litellm
              port: 4000
          middlewares:
            - name: auth
        - match: Host(`litellm.${DOMAIN}`)
          kind: Rule
          services:
            - name: litellm
              port: 4000

services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-latest
    environment:
      DATABASE_URL: postgres://${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_NAME}@pg.${COMPOSE_PROJECT_NAME}.svc.cluster.local/${COMPOSE_PROJECT_NAME}
      REDIS_HOST: redis.${COMPOSE_PROJECT_NAME}.svc.cluster.local
      REDIS_PORT: 6379
      STORE_MODEL_IN_DB: "True"
    command:
      - --config
      - /app/config.yaml
      - --host
      - "::"
      - --port
      - "4000"
    ports:
      - 4000
    volumes:
      - ./conf.yml:/app/config.yaml:ro

  pg:
    image: docker.io/library/postgres:18
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${COMPOSE_PROJECT_NAME}
    ports:
      - 5432
    volumes:
      - /var/lib/local/litellm:/var/lib/postgresql

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    ports:
      - 6379
    volumes:
      - data:/data

volumes:
  data:
