---
services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-latest
    environment:
      LANGFUSE_HOST:
      REDIS_HOST: redis://redis:6379
    ports:
      - 3080
    volumes:
      - ./litellm_config.yml:/app/librechat.yaml:ro

  redis:
    image: ghcr.io/valkey-io/valkey:latest
    labels:
      kompose.controller.type: statefulset
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:
