# https://docs.litellm.ai/docs/proxy/config_settings
# https://github.com/BerriAI/litellm/tree/main/litellm/proxy/example_config_yaml
---
litellm_settings:
  success_callback:
    - langfuse
  callbacks:
    - otel

general_settings:
  otel: true
  pass_through_endpoints:
    - &passthrough
      forward_headers: true
      path: /messages
      target: https://
    - <<: *passthrough
      path: /messages
      target: https://

model_list: []
