---
x-networkpolicy:
  - bifrost
  - crawl4ai
  - invidious
  - librechat
  - mcp
  - redlib
  - rss-bridge
  - searx
  - servarr

services:
  proxy:
    image: docker.io/library/nginx:latest
    labels:
      kompose.controller.type: statefulset
      kompose.volume.type: hostPath
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --location
        - --no-progress-meter
        - --output
        - /dev/null
        - --max-time
        - "1"
        - --proxy
        - socks5://localhost
        - --
        - http://${DOMAIN}/204
    ports:
      - 1080
    configs:
      - source: conf
        target: /etc/nginx/nginx.conf
    volumes:
      - /run/local/nginx:/run/local/nginx:ro

configs:
  conf:
    file: ./proxy.nginx
